// code_library.js
// This file stores snippets generated by the AI for future use.

const codeLibrary = {};

function saveCodeToLibrary(title, code) {
    chrome.storage.local.get(['savedCodeLibrary'], (res) => {
        let library = res.savedCodeLibrary || {};
        library[title] = { code, time: new Date().toLocaleTimeString() };
        chrome.storage.local.set({ savedCodeLibrary: library }, () => {
            console.log("Code saved to library:", title);
        });
    });
}

function getCodeFromLibrary(title, callback) {
    chrome.storage.local.get(['savedCodeLibrary'], (res) => {
        let library = res.savedCodeLibrary || {};
        callback(library[title]);
    });
}

// Example of saving a snippet
// saveCodeToLibrary('Hide Element', 'document.getElementById("target").style.display = "none";');
